// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwzfG3UgEuGk4kKr_8bO3NrNfvGZBpQno',
    appId: '1:1032180179434:web:89d7ceb0ce91c154a51293',
    messagingSenderId: '1032180179434',
    projectId: 'work-expo2-1',
    authDomain: 'work-expo2-1.firebaseapp.com',
    storageBucket: 'work-expo2-1.firebasestorage.app',
    measurementId: 'G-7SVKWFPCKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_-jdXbshwDN-z5Dj2wyINyuQxGP8g3wY',
    appId: '1:1032180179434:android:b1cb95f2eb8d764fa51293',
    messagingSenderId: '1032180179434',
    projectId: 'work-expo2-1',
    storageBucket: 'work-expo2-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO0mK9ow_b4RS2s6wzx70lO40Anxvk5NY',
    appId: '1:1032180179434:ios:78cdd9e565dab9d6a51293',
    messagingSenderId: '1032180179434',
    projectId: 'work-expo2-1',
    storageBucket: 'work-expo2-1.firebasestorage.app',
    iosBundleId: 'com.example.appAttempt1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO0mK9ow_b4RS2s6wzx70lO40Anxvk5NY',
    appId: '1:1032180179434:ios:78cdd9e565dab9d6a51293',
    messagingSenderId: '1032180179434',
    projectId: 'work-expo2-1',
    storageBucket: 'work-expo2-1.firebasestorage.app',
    iosBundleId: 'com.example.appAttempt1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwzfG3UgEuGk4kKr_8bO3NrNfvGZBpQno',
    appId: '1:1032180179434:web:87a17cbde73cbf77a51293',
    messagingSenderId: '1032180179434',
    projectId: 'work-expo2-1',
    authDomain: 'work-expo2-1.firebaseapp.com',
    storageBucket: 'work-expo2-1.firebasestorage.app',
    measurementId: 'G-119HPS9FEX',
  );

}